# Generated by Django 5.0.6 on 2025-11-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionBonita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('case_id', models.CharField(max_length=100)),
                ('proceso', models.CharField(max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sesión Bonita',
                'verbose_name_plural': 'Sesiones Bonita',
            },
        ),
    ]
